import { createCustomerInvoice } from "~/domain/customer-invoices";
import { createFiscalSubmission } from "~/domain/fiscal-submissions";
import type { DemoData, Teacher } from "~/domain/models";
import { publicTeacherAssets } from "~/infrastructure/teacher-assets";
import { addDays, localDateKey } from "~/lib/dates";

const weekdays = [1, 2, 3, 4, 5, 6].map((weekday) => ({
  weekday,
  startTime: "08:00",
  endTime: "18:00",
}));

const teachers: Teacher[] = [
  [
    "toni",
    "Toni Planells",
    "CEO y fundador",
    "master_teacher",
    "#1e6b55",
    publicTeacherAssets.toniPlanells,
  ],
  [
    "nico",
    "Nico Loprete",
    "Director general · Head Pro",
    "head_teacher",
    "#e86f51",
    publicTeacherAssets.nicoLoprete,
  ],
  [
    "giovanni",
    "Giovanni Quaquarelli",
    "Profesional PGA",
    "teacher",
    "#527d9f",
    publicTeacherAssets.giovanniQuaquarelli,
  ],
  [
    "nuria",
    "Nuria Elizo",
    "Profesora",
    "teacher",
    "#9c6a85",
    publicTeacherAssets.nuriaElizo,
  ],
  [
    "marcelo",
    "Marcelo Cuartero",
    "Instructor · Fitness",
    "teacher",
    "#b68b3c",
    publicTeacherAssets.marceloCuartero,
  ],
].map(([id, name, publicRole, category, color, photoUrl]) => ({
  id: `teacher-${id}`,
  name: String(name),
  photoUrl: String(photoUrl),
  email: `facturacion.${String(id)}@golfnaturalguidance.com`,
  fiscalName: `${String(name)} Golf Services`,
  fiscalId: `X${String(id).padEnd(7, "0").slice(0, 7).toUpperCase()}A`,
  fiscalAddress: "C/ del Golf, 1 · 07013 Palma de Mallorca",
  invoiceSeries: `GNG-${String(id).toUpperCase()}`,
  publicRole: String(publicRole),
  category: category as Teacher["category"],
  active: true,
  availability: weekdays,
  color: String(color),
}));

function at(dayOffset: number, time: string) {
  return `${localDateKey(addDays(new Date(), dayOffset))}T${time}:00`;
}

export function createSeed(): DemoData {
  const activities = [
    {
      id: "activity-green-explorers",
      productId: "product-group",
      name: "Green Explorers",
      description: "Aprender jugando en un grupo reducido y dinámico.",
      price: 45,
      memberPrice: 40,
      capacity: 8,
      teacherId: "teacher-nuria",
      startsAt: at(2, "10:00"),
      endsAt: at(2, "11:30"),
      active: true,
      requiresOnlinePayment: true,
      color: "#d5a84b",
    },
    {
      id: "activity-swing-lab",
      productId: "product-group",
      name: "Swing Lab",
      description:
        "Sesión de análisis técnico con vídeo y feedback personalizado.",
      price: 60,
      memberPrice: 55,
      capacity: 6,
      teacherId: "teacher-giovanni",
      startsAt: at(4, "16:00"),
      endsAt: at(4, "17:30"),
      active: true,
      requiresOnlinePayment: true,
      color: "#527d9f",
    },
    {
      id: "activity-junior",
      productId: "product-group",
      name: "Junior Academy · Aprende",
      description: "Programa semanal para jóvenes golfistas de 5 a 18 años.",
      price: 125,
      memberPrice: 115,
      capacity: 12,
      teacherId: "teacher-marcelo",
      startsAt: at(6, "09:30"),
      endsAt: at(6, "11:00"),
      active: true,
      requiresOnlinePayment: true,
      color: "#e86f51",
    },
  ];
  const data: DemoData = {
    teachers,
    products: [
      {
        id: "product-private",
        name: "Clase privada",
        description:
          "50 minutos de atención individual o compartida, adaptada a tu juego.",
        type: "private_lesson",
        durationMinutes: 50,
        playersMin: 1,
        playersMax: 4,
        active: true,
        reservable: true,
      },
      {
        id: "product-group",
        name: "Cursos y actividades",
        description: "Experiencias en grupo con plazas limitadas.",
        type: "group_course",
        durationMinutes: 90,
        playersMin: 1,
        playersMax: 1,
        active: true,
        reservable: true,
      },
      {
        id: "product-road-usa",
        name: "Road to USA",
        description: "Programa personalizado para estudiantes-deportistas.",
        type: "custom_program",
        durationMinutes: 60,
        playersMin: 1,
        playersMax: 1,
        active: true,
        reservable: false,
        priceOnRequest: true,
      },
    ],
    activities,
    students: [
      {
        id: "student-lucia",
        authUserId: "google-lucia",
        name: "Lucía Martín",
        email: "lucia@example.com",
        phone: "+34 600 123 456",
        fiscalId: "12345678Z",
        fiscalAddress: "C/ de la Marina, 18 · 07014 Palma de Mallorca",
      },
      {
        id: "student-mateo",
        name: "Mateo Serra",
        email: "mateo@example.com",
        fiscalId: "87654321X",
        fiscalAddress: "C/ del Mar, 24 · 07015 Palma de Mallorca",
      },
    ],
    leads: [
      {
        id: "lead-elena",
        name: "Elena Ruiz",
        email: "elena.ruiz@example.com",
        phone: "+34 622 416 802",
        source: "Formulario web",
        interest: "Clase privada de iniciación",
        stage: "new",
        score: 92,
        nextAction: "Enviar propuesta de primera clase",
        createdAt: at(-1, "11:20"),
      },
      {
        id: "lead-daniel",
        name: "Daniel Weber",
        email: "daniel.weber@example.com",
        source: "Google Maps",
        interest: "Bono de clases",
        stage: "qualified",
        score: 81,
        nextAction: "Compartir horarios con Toni",
        lastContactAt: at(-1, "16:10"),
        createdAt: at(-4, "10:30"),
      },
      {
        id: "lead-clara",
        name: "Clara Vidal",
        email: "clara.vidal@example.com",
        phone: "+34 651 901 244",
        source: "Instagram",
        interest: "Junior Academy",
        stage: "booking_pending",
        score: 74,
        nextAction: "Recordar la reserva de prueba",
        lastContactAt: at(-2, "18:00"),
        createdAt: at(-8, "12:00"),
      },
      {
        id: "lead-jaime",
        name: "Jaime Torres",
        email: "jaime.torres@example.com",
        source: "Recomendación",
        interest: "Swing Lab",
        stage: "booked",
        score: 98,
        nextAction: "Dar la bienvenida tras su primera reserva",
        lastContactAt: at(-1, "09:15"),
        createdAt: at(-12, "17:40"),
      },
    ],
    automationTasks: [
      {
        id: "automation-seed-elena",
        leadId: "lead-elena",
        title: "Responder a Elena Ruiz",
        detail: "Borrador con enlace a una clase de iniciación.",
        status: "suggested",
        createdAt: at(-1, "11:21"),
      },
      {
        id: "automation-seed-clara",
        leadId: "lead-clara",
        title: "Recordatorio para Clara Vidal",
        detail: "Seguimiento de la plaza de prueba en Junior Academy.",
        status: "ready",
        createdAt: at(-1, "18:05"),
      },
    ],
    bookings: [
      {
        id: "booking-seed-private",
        type: "private_lesson",
        studentId: "student-lucia",
        teacherId: "teacher-nico",
        productId: "product-private",
        startsAt: at(1, "10:00"),
        endsAt: at(1, "10:50"),
        playerCount: 1,
        memberType: "arabella_member",
        goal: "Juego corto",
        customerPrice: 85,
        teacherCompensation: 70.83,
        compensationRate: 85,
        status: "confirmed",
        paymentMethod: "online",
        paymentStatus: "paid",
        createdAt: new Date().toISOString(),
      },
      {
        id: "booking-seed-group",
        type: "group_activity",
        studentId: "student-mateo",
        teacherId: "teacher-nuria",
        productId: "product-group",
        activityId: "activity-green-explorers",
        startsAt: at(2, "10:00"),
        endsAt: at(2, "11:30"),
        playerCount: 1,
        memberType: "non_member",
        customerPrice: 45,
        teacherCompensation: 127.5,
        compensationRate: 85,
        status: "confirmed",
        paymentMethod: "online",
        paymentStatus: "paid",
        createdAt: new Date().toISOString(),
      },
    ],
    payments: [
      {
        id: "payment-seed-1",
        bookingId: "booking-seed-private",
        amount: 85,
        method: "online",
        status: "paid",
        createdAt: new Date().toISOString(),
      },
      {
        id: "payment-seed-2",
        bookingId: "booking-seed-group",
        amount: 45,
        method: "online",
        status: "paid",
        createdAt: new Date().toISOString(),
      },
    ],
    compensationLines: [
      {
        id: "line-seed-1",
        bookingId: "booking-seed-private",
        teacherId: "teacher-nico",
        hours: 0.83,
        rate: 85,
        amount: 70.83,
        status: "pending",
        createdAt: new Date().toISOString(),
      },
      {
        id: "line-seed-2",
        bookingId: "booking-seed-group",
        teacherId: "teacher-nuria",
        hours: 1.5,
        rate: 85,
        amount: 127.5,
        status: "pending",
        createdAt: new Date().toISOString(),
      },
    ],
    invoices: [],
    customerInvoices: [],
    fiscalSubmissions: [],
    settings: {
      timezone: "Europe/Madrid",
      currency: "EUR",
      slotIntervalMinutes: 60,
      privateLessonDuration: 50,
      noShowBillable: false,
      academyContact: {
        phone: "+34 678 808 435",
        email: "info@golfnaturalguidance.com",
        website: "www.golfnaturalguidance.com",
        location:
          "C/ Club de Golf Son Muntaner · Calle Miquel Lladó, s/n · 07013 Palma",
      },
    },
  };
  const customerInvoices = data.bookings.flatMap((booking) => {
    const teacher = data.teachers.find((item) => item.id === booking.teacherId);
    const student = data.students.find((item) => item.id === booking.studentId);
    if (!teacher || !student) return [];
    return [
      createCustomerInvoice(
        data,
        booking,
        student,
        teacher,
        data.activities.find((item) => item.id === booking.activityId),
        booking.createdAt,
      ),
    ];
  });
  return {
    ...data,
    customerInvoices,
    fiscalSubmissions: customerInvoices.map(createFiscalSubmission),
  };
}
